### ISSUE TITLE
Bridgegate and Pizzagate data link is broken

### ISSUE THREAD

**Issue by bryborge** [Roychowdhury-group/FENESTRA-Fake-News-Structure-and-Threat-Assessment#1]
In the readme, there is a link to some Bridgegate and Pizzagate data source, but I get a "Server Not Found" error in the browser.  Can that data be found elsewhere?  And if so, could you update the link in the readme to point to it?

Thank you!

**Comment by tango2** [comment]
Hi Bryan,
The doi, as noted in the article, is https://doi.org/10.25346/S6/VTFXSX
I'll ask our github guru to update the link.
Cheers,
Tim

**Comment by behnam354** [comment]
Thanks for reporting the issue. The link is updated now - closing the issue.

**Comment by bryborge** [comment]
Wonderful, thank you!
